=== Raphhache/TEI-XML_assignment_1/HACHE_assignment_1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Myletters (letter+)>
<!ELEMENT letter (author+, destination, body, place, date, url)>
<!ATTLIST letter id CDATA #REQUIRED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT destination (persName, placeName)>
<!ELEMENT persName (#PCDATA)>
<!ELEMENT placeName (#PCDATA)>
<!ELEMENT body (p+)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT place (#PCDATA)>
<!ELEMENT date (year)>
<!ATTLIST date when CDATA #REQUIRED>
<!ATTLIST date calendar (gregorian | persian) #REQUIRED>
<!ELEMENT year (#PCDATA)>
<!ELEMENT url (#PCDATA)>

=== Raphhache/TEI-XML_assignment_1/HACHE_assignment_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Myletters SYSTEM "HACHE_assignment_1.dtd">

<Myletters>
   <letter id="">
      <author></author>
      <destination>
         <persName></persName>
         <placeName></placeName>
      </destination>
      <body>
         <p></p>
      </body>
      <place></place>
      <date when="" calendar="persian">
         <year></year>
      </date>
      <url></url>
   </letter>
   
   <letter id="">
      <author></author>
      <destination>
         <persName></persName>
         <placeName></placeName>
      </destination>
      <body>
         <p></p>
      </body>
      <place></place>
      <date when="" calendar="persian">
         <year></year>
      </date>
      <url></url>
   </letter>
   
   <letter id="">
      <author></author>
      <destination>
         <persName></persName>
         <placeName></placeName>
      </destination>
      <body>
         <p></p>
      </body>
      <place></place>
      <date when="" calendar="persian">
         <year></year>
      </date>
      <url></url>
   </letter>
</Myletters>
